- Simple Snake Game
To create a Snake Game in Python. There will be walls around the edges which if the snake touches will lead to a game over.
> Snake Game

- Simple Snake Game
Reverts SamarthTech/python-and-AIML-projects-hacktoberfest24#1
Reason-Absence of necessary changes or commits required for a valid contribution. Please make a valid contribution.
> Revert "Snake Game"

- Digital Clock/DigitalClock.py
Added a digital clock  that shows time in Hours : Minutes : Secs  AM/PM format.
Along with the current date.
> Added a Digital Clock

- Python Calculator/Python Calculator codes.txt
- Python Calculator/calculator.py
Calculate any two numbers using python calculator.
> Add Python calculator

- 2048 Game/2048_game.py
The 2048 game project is the graphical implementation of one of the most popular sliding puzzle games by using Pygame, where the player can combine tiles with the same numbers to reach the tile with the number 2048 in the navigable 4x4 grid. The features of the game are a scoring system, smooth animations, and colorful bright look. After losing, the player can choose replay or quit, showing his final score. It involves interactivity and visualization of basic mechanisms and game logic using a Python code.
> 2024 Game implementation using pygames

- password_generator/README.md
- password_generator/main.py
> password_generator

- Hangman Game/hang.py
I, Nachiket Jain, developed a Hangman game in Python to enhance my programming skills. The game randomly selects a fruit name from a predefined list, allowing players to guess letters. I implemented input validation and a countdown of chances, creating an engaging experience. As players guess letters, the correctly guessed ones are displayed, while incorrect attempts decrease their chances. This project was not only fun but also a valuable exercise in logic and user interaction in programming!
> Hangman Game

- drwaing-slate/main.py
> Now how to draw:
- Press 'Space' to move Forward
- Press 'Tab' to move Backward
- Press 'p' to turn Counter Clockwise
- Press 'n' to turn Clockwise
- Press 'r' , 'g' , 'b' to change the pen color in Red , Green and Blue respectively
- Press 'u' to return the pen color to the default color (Black)
- Press '+' and '-' to bolder and lighter the pen width respectively
- Press 'c' to reset the screen (to remove whatever you've drawn)
- Click on the slate to turn it off
> Draw with your keyboard

- Rock Paper Scissor/main.py
In this Python project, I, Nachiket Jain, created a classic Rock-Paper-Scissors game. I designed it so that players can compete against the computer, making their choice while the computer selects randomly. The program determines the winner based on traditional rules and allows for multiple rounds, making it a fun way to practice my programming skills!
> Rock Paper Scissors

- Simple AI Chatbot/.env
- Simple AI Chatbot/Readme.MD
- Simple AI Chatbot/main.py
As assigned earlier i have added my chatbot that has been built on streamlit and python.
> Added a chatbot built on python and streamlit

- Finance-tracker/finance_tracker.py
- Finance-tracker/transactions.csv
This PR introduces a new Python module, finance_tracker, designed to help users effectively manage their personal or business finances. Key features include:
Transaction tracking: Easily record income, expenses, and transfers.
Categorization: Organize transactions into customizable categories for better analysis.
Budgeting: Set spending limits and track progress towards financial goals.
Reporting: Generate detailed reports on spending patterns, income sources, and net worth.
Data visualization: Create charts and graphs to visualize financial trends.
This module provides a user-friendly interface and flexible options for customization. It is built using [mention relevant Python libraries or frameworks] and adheres to best practices for code quality and maintainability.
Additional …
> python finance tracker

- Mystery Rooms/file.py
This PR introduces a classic text-based adventure game where players navigate through different rooms, interact with the environment, and collect items. The game features a series of interconnected locations like a hall, kitchen, bedroom, and garden, each with its own unique description and items. Players can explore the rooms, pick up items, and check their inventory, all through simple typed commands. The game loop ensures a continuous immersive experience until the player chooses to quit. This project is a great example of Python's interactive potential for beginners.
> MysteryRooms Game added

- Speak The Meaning Of The Word/Speak The Meaning Of The Word.py
This Python script defines two classes, Speaking and GFG, that work together to create a small text-to-speech dictionary application.
Speaking class:
Handles converting text to speech using the gTTS (Google Text-to-Speech) library.
The speak method saves the speech as an mp3 file and plays it using the pygame library.
GFG class:
Communicates with an online dictionary API (Dictionary API).
The get_word_meaning method sends a GET request to fetch the definition of a given word.
The Dictionary method prompts the user for a word, fetches its meaning, and uses the Speaking class to read the definition aloud.
Required Libraries (pip):
requests – for making HTTP requests to fetch word meanings from the API.
gtts – for converting the text to speech.
pygame – for playing the audio.
pip install …
> Speak The Meaning Of The Word

- Vehicle movement detection/cars.xml
- Vehicle movement detection/main.py
- Vehicle movement detection/readme.md
- Vehicle movement detection/requirements.txt
This pull request introduces a Python-based vehicle movement detection system utilizing OpenCV. The project features real-time detection and tracking of vehicles in video streams, along with movement classification (stopped, slow, fast). Users can specify a region of interest (ROI) for detection and save the results to a file for further analysis.
Key functionalities include:
- Vehicle detection via webcam or recorded video.
- Motion tracking with simple centroid algorithms.
- Background subtraction and contours detection for accurate vehicle identification.
This implementation enhances the project's capabilities in traffic monitoring and analysis.
> Add Vehicle Movement Detection using OpenCV

- Tic Tac Toe game/Readme.md
- Tic Tac Toe game/main.py
Welcome to the **Tic-Tac-Toe** game! This Python-based game allows you to play a classic game of Tic-Tac-Toe against the computer.
- [Introduction](#introduction)
- [How to Play](#how-to-play)
- [Game Rules](#game-rules)
- [How to Run](#how-to-run)
- [Features](#features)
This is a simple implementation of the Tic-Tac-Toe game in Python. The player can play against the computer in a 3x3 grid. The player uses 'X' and the computer uses 'O'. The game ends when either player wins or the game is a draw.
1. The game is played on a 3x3 grid.
2. You (the player) will use 'X', and the computer will use 'O'.
3. Players take turns placing their marks (X or O) in empty cells.
4. The player must input a number from 1 to 9 to choose a spot on the grid.
5. The computer chooses a random spot from the …
> Tic Tac Toe game

- Weather-App/README.md
- Weather-App/main.py
This pull request is a new PR request for a Weather App
It includes a simple weather application developed using Python and Tkinter GUI.
The app allows users to access real-time weather information by entering their API key and a city name.
> Weather app GUI

- Particle-simulator/main.py
Issue:  #75 
#Particle Simulator
This PR introduces a particle simulation using Pygame and Matplotlib, allowing users to visualize particle movement in real time and track the average position of particles over time.
##Key Features
Particle Creation: Users can add particles to the simulation by clicking within the Pygame window. The simulation supports a maximum of 100 particles.
Particle Movement: Each particle is initialized with a random velocity and moves within the defined window, bouncing off the edges.
Real-Time Visualization: Matplotlib is integrated to plot the average position of all particles in real-time, updating dynamically as new particles are added and existing particles move.
User Interaction: The simulation responds to mouse clicks, allowing users to add particles …
> Added Particle-simulator with Real-Time Plotting

- Temperature-Convertor/new.py
To provide a convenient and efficient tool for users to convert temperatures between Celsius, Fahrenheit.
> added a temperature convertor

- Temperature Convertor/temperatureConvertor.py
Added a Temperature Convertor where the the user can choose to convert temperature between celsius , fahrenheit and kelvin scales.
> Temperature Convertor

- song-lyrics-extractor/LICENSE
- song-lyrics-extractor/README.md
- song-lyrics-extractor/main.py
- song-lyrics-extractor/requirements.txt
A lyrics extractor is used to take out the lyrics from a song. In our project, the user will provide the song name and the artist name and our program will then extract the lyrics of the song from a great resource called api.lyrics.ovh, using requests and JSON libraries.
> added Song Lyrics Extractor

- hash-cracker/LICENSE
- hash-cracker/README.md
- hash-cracker/main.py
Hash Cracker is a powerful, multi-threaded password cracking tool written in Python. It's designed to efficiently crack various types of password hashes using brute-force techniques.
> added Hash Cracker: Multi-threaded Password Cracker

- find-ip-address/LICENSE
- find-ip-address/README.md
- find-ip-address/main.py
This nifty little Python script is your ticket to the wonderful world of IP addresses! It's like a magic wand that reveals the secret identities of computers on the internet.
> added IP Address Finder

- python-dictionary-app/LICENSE
- python-dictionary-app/README.md
- python-dictionary-app/main.py
A sleek and user-friendly dictionary application built with Python and Tkinter.
> added Python Dictionary App

- restaurant-management-system/LICENSE
- restaurant-management-system/README.md
- restaurant-management-system/main.py
The Restaurant Management System is a simple GUI application built with Python and Tkinter. It allows restaurant staff to manage customer orders, calculate bills, and view sample bills in real-time.
> added Restaurant Management System

- InternetSpeedTool/LICENSE
- InternetSpeedTool/README.md
- InternetSpeedTool/main.py
Welcome to Internet Speed Tool, your go-to solution for testing internet speed and finding website IP addresses!
> added Internet Speed Tool

- realtime face detection/.gitignore
- realtime face detection/LICENSE
- realtime face detection/README.md
- realtime face detection/main.py
- realtime face detection/model/haarcascade_frontalface_default.xml
- realtime face detection/requirements.txt
This PR introduces a real-time face detection feature using OpenCV and Haar Cascade. The system captures live video feed from the webcam, detects faces in real-time, and highlights them with a rectangle.
- Added `face_detection.py` script that captures video from the webcam.
- Integrated Haar Cascade (`haarcascade_frontalface_default.xml`) for face detection.
- Converts video frames to grayscale and detects faces.
- Draws a rectangle around detected faces in each frame.
- Program terminates when the 'q' key is pressed.
1. Run the script using `python face_detection.py`.
2. Ensure the webcam opens and faces are detected.
3. Press 'q' to exit the program.
This feature enhances the application with basic face recognition capabilities, providing a foundation for further development in …
> Realtime Face Detection using OpenCV

- Telegram_Bot/main.py
- Telegram_Bot/readme.md
- Telegram_Bot/requirements.txt
This is a simple Telegram bot built using Python and the `python-telegram-bot` library. The bot responds to certain commands and messages to provide links to popular websites like YouTube, LinkedIn, Gmail, and GeeksforGeeks.
- `/start`: Greets the user and provides a welcome message.
- `/help`: Lists all available commands.
- `/youtube`: Sends the YouTube URL.
- `/linkedin`: Sends the LinkedIn URL.
- `/gmail`: Sends a placeholder message for the Gmail URL (customize it with your own link).
- `/geeks`: Sends the GeeksforGeeks URL.
- Handles unknown commands and text input by replying with a message.
- Python 3.7+
- `python-telegram-bot` library (v20 or higher)
1. Clone the repository or download the script.
2. Install dependencies:
```bash
pip install -r requirements.txt
```
3. Replace …
> Telegram Bot is added

- DNA_cryptography/decrypt.py
- DNA_cryptography/encrypt.py
- DNA_cryptography/readme.md
DNA chain based encryption + AES + ategnography. Allows users to hide senstive information inside any image.
> Added a new encryption project that uses a custom encryption technique

- Book_Recomender_System/Readme.md
- Book_Recomender_System/books_data.csv
- Book_Recomender_System/main.py
- Book_Recomender_System/requirements.txt
This project implements a basic book recommendation system that suggests similar books based on a given book title. The system utilizes TF-IDF (Term Frequency-Inverse Document Frequency) and cosine similarity to analyze and rank the most similar books in the dataset.
- **Data Analysis**: 
- Visualizes the distribution of average ratings using histograms.
- Displays the most popular authors through bar charts (currently commented out for simplicity).
- **Recommendation System**: 
- Provides book recommendations based on the cosine similarity of books' content (title and author combined).
- **Interactive Visualization**: 
- Leverages Plotly for interactive data visualizations, with sections commented out to maintain simplicity.
Two interactive visualizations can be enabled by uncommenting …
> Book Recommendation System

- Python Calculator/Python Calculator codes.txt
Updating the python calculator by using tkinter #40
> Update Python Calculator codes #40

- Hand-Detector/main.py
- Hand-Detector/readme.md
- Hand-Detector/requirements.txt
This project is a real-time hand tracking application that uses your computer's webcam to detect and visualize hand movements. Built with OpenCV and MediaPipe, it draws skeletal landmarks on your hands in a live video feed, making it useful for gesture recognition, motion tracking, and interactive applications.
> Added Hand Detector in Python

- mind-maze-adventure/LICENSE
- mind-maze-adventure/README.md
- mind-maze-adventure/main.py
A dynamic terminal-based maze game where the walls have a mind of their own! Race against time to reach the goal while navigating through a constantly shifting labyrinth.
> added Mind Maze Adventure

- text-based-time-travel-mystery/LICENSE
- text-based-time-travel-mystery/README.md
- text-based-time-travel-mystery/main.py
An interactive text-based adventure game where players journey through different time periods, interact with unique characters, and collect clues to unravel mysteries across history.
> added Time Travel Adventure Game

- quantum-state-puzzle/LICENSE
- quantum-state-puzzle/README.md
- quantum-state-puzzle/main.py
A challenging puzzle game where players must manipulate quantum states to match a target configuration. The game features a grid-based interface where toggling one state affects neighboring states, creating an engaging puzzle-solving experience.
> added Quantum State Puzzle

- typing-driven-rpg-battle-simulator/LICENSE
- typing-driven-rpg-battle-simulator/README.md
- typing-driven-rpg-battle-simulator/main.py
A text-based RPG battle game where players can cast spells, use items, and battle multiple enemies. The game features a save/load system, character progression, and various combat mechanics.
> added Typing-Driven RPG Battle Simulator

- Number_Game/number.py
`Instructions`
- Select Your Level.
- Guess A Number.
- You Have To Guess The Number Within The Steps, Corresponding To Your Level.
- Any Invalid Inputs May Cause The Game Closed.
> Added Number Game

- Rock,Paper ,Scissor/Rock,paper,scissor-game.py
Added a rock , paper, scissor game.
The code  asks the user if they want to play again after each game.
the user can play again by choosing yes(y).
The user can terminate the game whenever they want by choosing not to  play again(n).
> Added Rock,Paper,Scissor Game

- coffee-machine/.idea/.gitignore
- coffee-machine/.idea/coffee-machine.iml
- coffee-machine/.idea/inspectionProfiles/profiles_settings.xml
- coffee-machine/.idea/misc.xml
- coffee-machine/.idea/modules.xml
- coffee-machine/main.py
A python code representing a real world coffee machine
> Coffee-Machine
